name: Production workflow

on:
  push:
    branches:
      - production

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: github-actions-heroku-deploy

jobs:
  ui-test-and-deploy-to-prod:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        firefox:
          ["84.0", "latest-beta", "latest-devedition", "latest-esr", "latest"]
    name: Firefox ${{ matrix.firefox }} sample
    steps:
      - name: Setup firefox
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: ${{ matrix.firefox }}
      - run: |
          echo Installed firefox versions: ${{ steps.setup-firefox.outputs.firefox-version }}
          firefox --version

      - name: Checkout code
        uses: actions/checkout@v2

      - name: run firefox
        run: firefox --version && which firefox

      - name: Set up Node.js v 17
        uses: actions/setup-node@v1
        with:
          node-version: "17"

      - name: Install dependencies
        run: npm install

      - name: Run Selenium UI tests
        run: node src/ui_tests/test_calculator_sel.js

      - name: Build the app
        run: npm run build

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "github-actions-heroku-deploy"
          heroku_email: "adnagee@gmail.com"
